language: python
python:
  - "3.3"
install:
  - pip install -r requirements.txt
script: make travis
#after_success: coveralls
notifications:
  email: monu1618@gmail.com
  irc:
    channels:
    on_success: change
    on_failure: change
    use_notice: true
